// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'bn'
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'hi'
	| 'id'
	| 'it'
	| 'ja'
	| 'ko'
	| 'mr'
	| 'pt'
	| 'ru'
	| 'sw'
	| 'ta'
	| 'te'
	| 'tr'
	| 'ur'
	| 'vi'
	| 'zh-CN'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​n​g​l​i​s​h
	 */
	lang: string
	/**
	 * S​S​I​D​ ​/​ ​N​e​t​w​o​r​k​ ​I​D
	 */
	ssid: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	password: string
	/**
	 * E​n​c​r​y​p​t​i​o​n
	 */
	encryption: string
	/**
	 * H​i​d​d​e​n
	 */
	hidden: string
	/**
	 * P​r​i​n​t
	 */
	print: string
}

export type TranslationFunctions = {
	/**
	 * English
	 */
	lang: () => LocalizedString
	/**
	 * SSID / Network ID
	 */
	ssid: () => LocalizedString
	/**
	 * Password
	 */
	password: () => LocalizedString
	/**
	 * Encryption
	 */
	encryption: () => LocalizedString
	/**
	 * Hidden
	 */
	hidden: () => LocalizedString
	/**
	 * Print
	 */
	print: () => LocalizedString
}

export type Formatters = {}
