// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'bn'
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'hi'
	| 'id'
	| 'it'
	| 'ja'
	| 'ko'
	| 'mr'
	| 'pt'
	| 'ru'
	| 'sw'
	| 'ta'
	| 'te'
	| 'tr'
	| 'ur'
	| 'vi'
	| 'zh-CN'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​n​g​l​i​s​h
	 */
	lang: string
	/**
	 * S​S​I​D​ ​/​ ​N​e​t​w​o​r​k​ ​I​D
	 */
	ssid: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	password: string
	/**
	 * E​n​c​r​y​p​t​i​o​n
	 */
	encryption: string
	/**
	 * H​i​d​d​e​n
	 */
	hidden: string
	/**
	 * P​r​i​n​t
	 */
	print: string
	/**
	 * W​i​F​i​ ​Q​R​ ​C​o​d​e​s​ ​i​n​ ​S​e​c​o​n​d​s
	 */
	htmlTitle: string
	/**
	 * C​r​e​a​t​e​ ​W​i​F​i​ ​Q​R​ ​C​o​d​e​s​ ​i​n​ ​S​e​c​o​n​d​s​!
	 */
	ctaHeader: string
	/**
	 * S​h​a​r​i​n​g​ ​W​i​F​i​ ​c​r​e​d​e​n​t​i​a​l​s​ ​w​i​t​h​ ​a​ ​Q​R​ ​c​o​d​e​ ​m​a​k​e​s​ ​i​t​ ​e​a​s​y​ ​f​o​r​ ​y​o​u​r​ ​g​u​e​s​t​s​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​y​o​u​r​ ​W​i​F​i​ ​n​e​t​w​o​r​k​ ​w​i​t​h​o​u​t​ ​e​n​t​e​r​i​n​g​ ​a​ ​l​o​n​g​ ​a​n​d​ ​c​o​m​p​l​i​c​a​t​e​d​ ​p​a​s​s​w​o​r​d​.
	 */
	ctaDescription: string
	/**
	 * M​a​d​e​ ​b​y​ ​{​a​u​t​h​o​r​}
	 * @param {string} author
	 */
	authorship: RequiredParams<'author'>
	/**
	 * T​o​g​g​l​e​ ​T​h​e​m​e
	 */
	themeToggle: string
}

export type TranslationFunctions = {
	/**
	 * English
	 */
	lang: () => LocalizedString
	/**
	 * SSID / Network ID
	 */
	ssid: () => LocalizedString
	/**
	 * Password
	 */
	password: () => LocalizedString
	/**
	 * Encryption
	 */
	encryption: () => LocalizedString
	/**
	 * Hidden
	 */
	hidden: () => LocalizedString
	/**
	 * Print
	 */
	print: () => LocalizedString
	/**
	 * WiFi QR Codes in Seconds
	 */
	htmlTitle: () => LocalizedString
	/**
	 * Create WiFi QR Codes in Seconds!
	 */
	ctaHeader: () => LocalizedString
	/**
	 * Sharing WiFi credentials with a QR code makes it easy for your guests to connect to your WiFi network without entering a long and complicated password.
	 */
	ctaDescription: () => LocalizedString
	/**
	 * Made by {author}
	 */
	authorship: (arg: { author: string }) => LocalizedString
	/**
	 * Toggle Theme
	 */
	themeToggle: () => LocalizedString
}

export type Formatters = {}
