// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'bn'
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'hi'
	| 'id'
	| 'it'
	| 'ja'
	| 'ko'
	| 'mr'
	| 'pt'
	| 'ru'
	| 'sw'
	| 'ta'
	| 'te'
	| 'tr'
	| 'ur'
	| 'vi'
	| 'zh-CN'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​n​g​l​i​s​h
	 */
	lang: string
	/**
	 * S​S​I​D​ ​/​ ​N​e​t​w​o​r​k​ ​I​D
	 */
	ssid: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	password: string
	/**
	 * E​n​c​r​y​p​t​i​o​n
	 */
	encryption: string
	/**
	 * H​i​d​d​e​n
	 */
	hidden: string
	/**
	 * P​r​i​n​t
	 */
	print: string
	/**
	 * W​i​F​i​ ​Q​R​ ​C​o​d​e​s​ ​i​n​ ​S​e​c​o​n​d​s
	 */
	htmlTitle: string
	/**
	 * B​u​i​l​t​ ​b​y​ ​{​a​u​t​h​o​r​}
	 * @param {string} author
	 */
	authorship: RequiredParams<'author'>
	/**
	 * T​o​g​g​l​e​ ​T​h​e​m​e
	 */
	themeToggle: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
}

export type TranslationFunctions = {
	/**
	 * English
	 */
	lang: () => LocalizedString
	/**
	 * SSID / Network ID
	 */
	ssid: () => LocalizedString
	/**
	 * Password
	 */
	password: () => LocalizedString
	/**
	 * Encryption
	 */
	encryption: () => LocalizedString
	/**
	 * Hidden
	 */
	hidden: () => LocalizedString
	/**
	 * Print
	 */
	print: () => LocalizedString
	/**
	 * WiFi QR Codes in Seconds
	 */
	htmlTitle: () => LocalizedString
	/**
	 * Built by {author}
	 */
	authorship: (arg: { author: string }) => LocalizedString
	/**
	 * Toggle Theme
	 */
	themeToggle: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
}

export type Formatters = {}
